/*let a=8, b=3, x=5,y="10";
let c=a+b;
document.write("c="+(a+b));
document.write("a+b="+(a+b));
document.write("a-b="+(a-b));
document.write("a/b="+(a/b));
document.write("a%b="+(a%b));
document.write("a**b="+(2**3));
document.write("a>b="+(a>b));
console.log("a<b="+(a<b));
console.log("x==y ="+(x==y));
console.log("x===y ="+(x===y));
console.log("x!=y ="+(x!=y));
console.log("x!==y =" +(x!==y));
var i=10,j=5,k=5;
console.log((i>j)&&(j==k));
console.log((i<j)||(j!=k));
//console.log((i>j)!(j==k));*/
var a=10,b=5,c="ring";
console.log("1. a=10,b=5,c='ring'");
console.log((a===b)&&(a<b)&&(b<c));
var a=5,b=8,c=9;
console.log("2. a=5,b=8,c=9;");
console.log((a>=b)||(c!=a));
var a="world",b=5,c=34;
console.log("3. a='world',b=5,c=34;");
console.log((a!=c)||(c>a)||(c===b));
var a=12,b=8,c=5;
console.log("4.a=12,b=8,c=5;");
console.log((a<=b)&&(c>a)&&(a!==c));
var a='5',b='hello',c=8;
console.log("5.a='5',b='hello',c=8;");
console.log((a+b)&&(a>b)&&(c==b));
var a=4,b=5;
console.log("6.a=4,b=5");
console.log((a!=b)&&(a<b));
var a=2,b=4,c=3;
console.log("7.a=2,b=4,c=3");
console.log((a==b)&&(b==c));
var a=4,b=2,c=3;
console.log("8.a=4,b=2,c=3");
console.log((a*b)&&(b*c)&&(c*a));
var a=4,b=2,c=3;
console.log("9.a=4,b=2,c=3");
console.log((a+b)&&(b+c)&&(c+a));
var a=4,b=2,c=3;
console.log("10.a=4,b=2,c=3");
console.log((a*b)||(b*c)||(c*a));
var a=4,b=2,c=3;
console.log("11.a=4,b=2,c=3");
console.log((a+b)||(b+c)||(c+a));
var a=2,b=3,c=4;
console.log("12.a=2,b=3,c=4");
console.log((a<b)||(b<c)||(a<c));
var a=4,b=5;
console.log("12.a=4,b=5");
console.log((a!=b)&&(a<b));
var a=4,b=5;
console.log("13.a=4,b=5");
console.log((a!=b));
var a=5,b=5;
console.log("14.a=5,b=5");
console.log((a!=b));
var a=4,b='5';
console.log("15.a=4,b='5'");
console.log((a!==b));
var a='5',b='5';
console.log("15.a='5',b='5'");
console.log((a!==b));
var a='15',b='5';
console.log("15.a='15',b='5'");
console.log((a!==b));
var a="vaishu", b="shalu";
console.log((a>b));
var a="vaishu", b="5672462883489785283";
console.log((a>b));
